// Filename: internal/data/jobs.go
package data

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"time"

	"github.com/lib/pq"
)

// ReportPayload struct represents the payload for a report job,
// containing the from and to dates for the report.
type ReportPayload struct {
	From time.Time `json:"from"`
	To   time.Time `json:"to"`
}

type ReportJob struct {
	ID         string `json:"-"`
	PublicID   string `json:"id"`
	ConsumerID string `json:"consumer_id"`
	// Represents who the job is for.
	// This is useful if we have an authentication system
	// and we want to ensure that only the correct consumer can access their own reports.
	JobType string `json:"job_type"`
	// Represents the type of job. In this case, it's a "consumer_activity_report".
	// This would be important if we had multiple types of jobs in the system,
	// so we can differentiate between them.
	Status string `json:"status"`
	// Represents the current status of the job.
	// Important for the client to know if the job is still queued, processing, completed, or failed.
	// We usually observe the status when we poll for it
	Payload ReportPayload `json:"payload"`
	// Represents the input data for the job. In this case, it's the from and to dates for the report.
	Result json.RawMessage `json:"result,omitempty"`
	// Represents the output data of the job. In this case, it's the generated report data.
	ErrorMessage *string `json:"error_message,omitempty"`
	// StartedAt and CompletedAt are used to track when the job started and completed.
	// We can use this to see how long a job takes.
	// StartedAt and CompletedAt will be nil if the job has not started or completed yet.
	// Therefore, they are pointers to allow for null values.
	StartedAt   *time.Time `json:"started_at,omitempty"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// CreatedAt is used to track when the job was created.
	// This is useful for our job queue.
	// We want jobs to be processed in the order they were created,
	// so we can use this timestamp to sort them.
	CreatedAt time.Time `json:"created_at"`
}

type ReportJobModel struct {
	DB *sql.DB
}

// When we create a job, we begin the job lifecycle.
// All jobs start in the "queued" state when they are first inserted.
// The other models are responsible for contuining the job lifecycle, moving the job through
// the various states until it is completed or failed.
// Our postgres database handles the durable job state.
func (m ReportJobModel) InsertReportJob(job *ReportJob) error {
	// We need to marshal the Payload struct into JSON so we can store it in the database.
	payload, err := json.Marshal(job.Payload)
	if err != nil {
		return err
	}
	// The application supplies these three values to PostgreSQL:
	// $1 = consumer ID
	// $2 = job type
	// $3 = JSON-encoded job payload.
	// id, public_id, status, and created_at are not supplied by the application
	// in the INSERT, so they are generated or defaulted by the database.

	query := `INSERT INTO report_jobs (consumer_id, job_type, payload)
		VALUES ($1, $2, $3) RETURNING id, public_id, status, created_at`
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	// We return ID, PublicID, Status, and CreatedAt from the database after the INSERT operation.
	// We use QueryRowContext to execute the query and scan the returned values into the job struct.
	// This populates the job struct with the values generated by the database
	// Now we have the complete job struct in memory.
	err = m.DB.QueryRowContext(ctx, query, job.ConsumerID, job.JobType, payload).Scan(
		&job.ID, &job.PublicID, &job.Status, &job.CreatedAt,
	)
	if err != nil {
		var pgErr *pq.Error
		if errors.As(err, &pgErr) && pgErr.Code == "23503" {
			return ErrRecordNotFound
		}
		// A 23503 error is a foreign-key violation. This indicates that
		// jobs.consumer_id must reference an existing consumer in the consumers table.
		// If we get this error, it means that the job we're creating is referencing a consumer
		// that doesn't exist in the database.
		return err
	}
	return nil
}

// This function is used to poll for a job by its public ID.
// This is useful for clients to check the status of a job they created.
func (m ReportJobModel) GetReportJobByPublicID(publicID string) (*ReportJob, error) {
	query := `SELECT id, public_id, consumer_id, job_type, status, payload,
		COALESCE(result, 'null'::jsonb), error_message, started_at, completed_at, created_at
		FROM report_jobs WHERE public_id = $1`
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()
	var job ReportJob
	var payload []byte
	err := m.DB.QueryRowContext(ctx, query, publicID).Scan(&job.ID, &job.PublicID,
		&job.ConsumerID, &job.JobType, &job.Status, &payload, &job.Result,
		&job.ErrorMessage, &job.StartedAt, &job.CompletedAt, &job.CreatedAt)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, ErrRecordNotFound
		}
		return nil, err
	}
	if err := json.Unmarshal(payload, &job.Payload); err != nil {
		return nil, err
	}
	return &job, nil
}

// When we have a worker that is polling for jobs, we want to claim the next job in the queue.
// In the lifecycle, we're looking for jobs that are in the "queued" state, and we want to claim
// them and move them to the "processing" state.
func (m ReportJobModel) ClaimNextReportJob(ctx context.Context) (*ReportJob, error) {
	// When we have multiple workers trying to claim jobs from the queue,
	// we need to ensure that only one worker can claim a job at a time.
	// To do this, we use a database transaction with the FOR UPDATE SKIP LOCKED clause.
	// This allows us to lock the row for the job we're claiming, which disallows another
	// worker to claim the same job.
	tx, err := m.DB.BeginTx(ctx, nil)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()
	// WHERE status = 'queued' is the condition to only select jobs that are in the queued state.
	// This ensures we only claim jobs that are unclaimed.
	// AND job_type = 'consumer_activity_report' is the condition to only select jobs of the type "consumer_activity_report".
	// ORDER_BY created_at ensures that we claim jobs in the order they were created,
	// This is the main purpose for the created_at field.
	// FOR UPDATE locks the selected job row so another worker cannot
	// simultaneously acquire a conflicting lock and claim the same job.
	// SKIP LOCKED means that if the job we're trying to claim is already locked by
	// another worker, we skip it and move on to the next job.
	// SELECTING and UPDATING the job in the same transaction ensures that we don't have a
	// conflict where two workers select the same job and both try to update it to
	// "processing" at the same time.
	// If we select first and then update later, a conflict can occur where a 2nd worker
	// selects the same job before the first worker updates it to "processing".
	query := `SELECT id, public_id, consumer_id, job_type, payload FROM report_jobs
		WHERE status = 'queued' AND job_type = 'consumer_activity_report'
		ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1`
	var job ReportJob
	var payload []byte
	// When there are no jobs in the queue, QueryRowContext will return sql.ErrNoRows.
	// We do not want to treat this as an error, so we check for it and return nil instead.
	// This allows the worker to continue polling for jobs without crashing.
	if err := tx.QueryRowContext(ctx, query).Scan(&job.ID, &job.PublicID,
		&job.ConsumerID, &job.JobType, &payload); err != nil {
		return nil, err
	}
	if err := json.Unmarshal(payload, &job.Payload); err != nil {
		return nil, err
	}
	if _, err := tx.ExecContext(ctx,
		`UPDATE report_jobs SET status = 'processing', started_at = now() WHERE id = $1`, job.ID); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	// If all is successful the job life cycle transitions from "queued" to "processing".
	// We then return the job to the worker.
	job.Status = "processing"
	return &job, nil
}

// There are 2 final states in the job lifecycle.
// A job can either be completed or failed.

// MarkCompleted is used to mark a job as completed and store the result of the job.
func (m ReportJobModel) MarkCompletedReportJob(ctx context.Context, id string, result []byte) error {
	_, err := m.DB.ExecContext(ctx,
		`UPDATE report_jobs SET status = 'completed', result = $2, completed_at = now() WHERE id = $1`,
		id, result)
	return err
}

// MarkFailed is used to mark a job as failed and store the error message.
func (m ReportJobModel) MarkFailedReportJob(ctx context.Context, id, message string) error {
	_, err := m.DB.ExecContext(ctx,
		`UPDATE report_jobs SET status = 'failed', error_message = $2, completed_at = now() WHERE id = $1`,
		id, message)
	return err
}
